### ISSUE TITLE
Virtual Environment for Raspiled

### ISSUE THREAD

**Issue by prometheus3995** [michaeljtbrooks/raspiled#3]
Hi,
Thanks for the great how to. 
I have made the hardware and got it all working exactly how i need it. I have only 1 Issue, in your instructions you say 

> If you want the Raspberry Pi to boot up and automatically run Raspiled, you can add this command to /etc/rc.local:

> /path/to/your/virtualenv/python

 /path/to/your/raspiled/src/raspiled_listener.py 

I have never used virtual environments before, so i followed your instructions in step 6 exactly. 

> virtualenv ./

> source ./bin/activate

What i would like to know is what should the path to the virtual environment be?

> /path/to/your/virtualenv/python /path/to/your/raspiled/src/raspiled_listener.py 

Thanks

**Comment by josuemtzmo** [comment]
Hello Prometheus,

Replace `/path/to/your/virtualenv/` by the global path of `./bin/activate`, you can run the command `ls ./bin/` and you will find a python executable. That's the one which you should use to run `raspiled_listener.py`.

**Comment by prometheus3995** [comment]
> ./bin/activate/python /Dev/raspiled/src/raspiled_listener.py 

Like that above?

**Comment by michaeljtbrooks** [comment]
Well done on building this! I'm glad you could make sense of our how to!

Commands from rc.local are executed as the root (admin) user. Since
rc.local is located in /etc, you should give it an absolute path rather
than a relative path

e.g.
   /Dev/raspiled/bin/activate/python  /Dev/raspiled/src/raspiled_listener.py

That's a bit like saying "python raspiled_listener.py" to run that listener
script, just with absolute paths which make sure the right virtual
environment is used.

If you get any trouble with it not running or throwing errors, try this
commit version of the code:
https://github.com/michaeljtbrooks/raspiled/tree/f6f44f035a748c528c09f3d065f18cb1cc87a031

The reason for this is that we've been merging some changes in to
incorporate some brilliant features Josue has built. There are a few little
fixes I want to do on the merged code when I find some more time.

---------------------------------------------------------------------
Dr. Michael Brooks
(MA Cantab. MB BChir Cantab.)
Emergency Medicine Doctor (Staff Grade / SpR)

Chief Medical Officer - PatientSource
http://www.patientsource.co.uk

---------------------------------------------------------------------

**Comment by michaeljtbrooks** [comment]
Clarified Readme to explain the absolute paths with an example.

**Comment by prometheus3995** [comment]
Hi Micheal,
This is the first chance I have had to try your suggestion out. 
I have changed rc.local to the absolute path, but I am unable to get it working from boot.
A couple of questions

- Does it have to run in a virtualenv?
if it does have to run in virtualenv, do I have to add in rc.local the 

> virtualenv ./
command as well?

- can I have a link to the control page from another page?
I have a webpage that controls multiple relays (on/off), one of these turns the led strip on/off, I want to have a second page which is where the colour control is. I have created the link from <my.pi.ip.addr> to <my.pi.ip.iddr>:9090. instead of it being directed to another port, can it be directed to another webpage. eg <my.pi.ip.addr>/colour_control.html?
