### ISSUE TITLE
Raspiled Testing 

### ISSUE THREAD

**Issue by josuemtzmo** [michaeljtbrooks/raspiled#6]
Hello Michael,

Could you please test the dev branch in order to know if it works properly for you. So far It will ask you for authentication and also now you can schedule alarms. I will implement some interactions with Mopidy (Spotify) in the future.

Cheers,
Josue

**Comment by michaeljtbrooks** [comment]
I've taken your latest changes, made a few minor amendments and pulled back into master. It's working for me!

**Comment by Flowsche** [comment]
All functions working for me too after the latest changes in master 8) Nice work!
I re-added the old "Campfire" as a second variant in my settings, its a smoother one like the fish tank. the newer is a little bit more flickering, doesn't fit for a long led strip I think.

**Comment by michaeljtbrooks** [comment]
Great to hear! I've just merged in some more small things so that you can get the current status of the strip by hitting your.ip.addr.ess:pi_port/status, and what the Raspiled internal API can do your.ip.addr.ess:pi_port/capabilities (in JSON).

Feel free to invent some sequences of your own! Most of my ones were just me pissing about. I've only ever used "Fish Tank" and "Party" sequences for any real length of time. Let's be honest, nobody in their right mind would sit there with NeeNaw USA running all evening!
Most of the time I use "Red" or "Candle".  

When I next get a chance, I'm going to hive some of the Web Server logic off into a base class, so that it can be reused in other Raspberry Pi web controlled things easily. You may have seen my Raspitherm project which borrows heavily from Raspiled. I'm now controlling my home heating through a Raspberry Pi too!
